;
; DZ80 configuration file for sys2.bin
; Generated by DZ80 V3.4.1 on 2024/12/26 02:48
;
o 4d00		; program offset
i 0000-4cff	; Invalid data
c 4d00-4e76	; Code space
c 4e77-4e7e	; 8-bit data
c 4e7f-5187	; Code space
b 5188-51ac
